dependencies:
  - name: mongodb
    version: 0.4.9
    repository: https://kubernetes-charts.storage.googleapis.com
    condition: mariadb.enabled
  - name: redis
    version: 1.1.19
    repository: https://kubernetes-charts.storage.googleapis.com
    condition: redis.enabled
  - name: elasticsearch
    version: 2.0.2
    repository: https://charts.bitnami.com/bitnami
    condition: elasticsearch.enabled